"""Tests for resume document parsing."""

from __future__ import annotations

import pytest

from src.processing.document_parser import (
    DocumentParseError,
    extract_pdf_text,
    extract_text,
    looks_like_pdf,
)


def build_pdf(text: str) -> bytes:
    """Build a minimal single-page PDF containing ``text``.

    Hand-built rather than generated by a library so the test suite needs no
    extra dependency and no fixture files on disk.
    """
    content = f"BT /F1 24 Tf 72 700 Td ({text}) Tj ET".encode("latin-1")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length " + str(len(content)).encode() + b" >>\nstream\n" + content + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    ).encode()
    return bytes(out)


# --- type detection --------------------------------------------------------


def test_pdf_is_detected_from_content_not_filename():
    assert looks_like_pdf(build_pdf("Hello")) is True
    assert looks_like_pdf(b"Just some text") is False


# --- PDF path --------------------------------------------------------------


def test_text_is_extracted_from_a_pdf():
    extracted = extract_pdf_text(build_pdf("Python Engineer"))
    assert "Python" in extracted


def test_a_pdf_routes_through_extract_text():
    assert "Python" in extract_text(build_pdf("Python Engineer"))


def test_corrupt_pdf_bytes_raise_a_parse_error():
    with pytest.raises(DocumentParseError, match="Could not read PDF"):
        extract_pdf_text(b"%PDF-1.4 this is not really a pdf")


def test_a_pdf_with_no_extractable_text_is_reported_clearly():
    """Scanned resumes are a real case; the message must say why it failed."""
    with pytest.raises(DocumentParseError, match="OCR"):
        extract_text(build_pdf(""))


# --- text path -------------------------------------------------------------


def test_plain_utf8_text_is_returned():
    assert extract_text(b"Jane Smith\nPython, SQL") == "Jane Smith\nPython, SQL"


def test_utf8_characters_survive():
    assert extract_text("Siân — Ingeniería".encode()) == "Siân — Ingeniería"


def test_surrounding_whitespace_is_stripped():
    assert extract_text(b"  \n  Python  \n  ") == "Python"


def test_empty_upload_is_rejected():
    with pytest.raises(DocumentParseError, match="empty"):
        extract_text(b"")


def test_whitespace_only_upload_is_rejected():
    with pytest.raises(DocumentParseError, match="no text"):
        extract_text(b"   \n\t  ")


def test_binary_that_is_not_a_pdf_is_rejected_with_guidance():
    with pytest.raises(DocumentParseError, match=r"Supported: \.pdf, \.txt, \.md"):
        extract_text(b"\xff\xfe\x00\x01\x02binary\x80\x81")
